### PR TITLE
APyFloat longer formats

### PR DESCRIPTION
**Pull request by Theodor-Lindberg**

### CODE REVIEW

**Comment by Theodor-Lindberg** [comment]
Current TODO:
* [ ] Some cases of division rounds to 0 instead of the smallest subnormal. E.g. $0.001953125 / 1.125$ (`APyFloat(sign=0, exp=0, man=1, exp_bits=4, man_bits=3) / APyFloat(sign=0, exp=7, man=1, exp_bits=4, man_bits=3)`)
* [ ] Quantization of mantissa should be handled in APyFixed (for now) for addition/subtraction as the result could exceed the 52-bit limit that comes from the double-conversion.
* [ ] Fix choice between fast path and slow path in multiplication.

Some simple test cases have been implemented, but more extensive tests will be created in near future.

**Comment by Theodor-Lindberg** [comment]
@oscargus Do you want me to resolve the bug mentioned in the comment above before merging or should I create an issue and fix afterwards? I refer to the bug regarding that division sometimes quantizes to 0 instead of the smallest subnormal number.

**Comment by oscargus** [comment]
Always merge all improvements quickly. :-) 

I guess that this doesn't introduce that bug, but it was there before?

**Comment by Theodor-Lindberg** [comment]
> Always merge all improvements quickly. :-)
> 
> I guess that this doesn't introduce that bug, but it was there before?

Done!

I think it was introduced when changing how numbers were casted to subnormals, as it now respect the quantization mode.

**Pull request merged**
