### PR TITLE
Tweak control path of mantissa quantization

### PR DESCRIPTION
**Pull request by Theodor-Lindberg**
Hopefully it improves the performance.

### CODE REVIEW

**Comment by oscargus** [comment]
I'm wondering if one should include the computation of G and T inside each case as well? (The ones that are actually required.) Probably one will see the main benefit when moving the carry-check inside this as well.

**Comment by oscargus** [comment]
Looks like this is slightly slower. However, moving the carry check in may change that.

**Comment by oscargus** [comment]
I think that maybe it makes sense to use lambdas that either are passed along or looked up in an array (enums are integers, so more a matter of keeping track of indices etc). Passing along may require a bit of refactoring though if we want to avoid multiple lookups in case of e.g. matrix multiplication, but for now, using this approach internally in array operations should speed things up(?).

**Comment by Theodor-Lindberg** [comment]
> I think that maybe it makes sense to use lambdas that either are passed along or looked up in an array (enums are integers, so more a matter of keeping track of indices etc). Passing along may require a bit of refactoring though if we want to avoid multiple lookups in case of e.g. matrix multiplication, but for now, using this approach internally in array operations should speed things up(?).

I think that makes sense. Although function pointers are slower than normal functions in general, not having to use the switch-statement each time for the arrays could speed things up.

**Comment by Theodor-Lindberg** [comment]
> Looks like this is slightly slower. However, moving the carry check in may change that.

Hm okay, I will try passing the "two" to the function and also a reference to the exponent such that it can be updated.

**Comment by oscargus** [comment]
I think that this can be closed when #383 is merged. Then one can check if one can write the separate quantization functions in a more efficient way.

**Comment by Theodor-Lindberg** [comment]
> I think that this can be closed when #383 is merged. Then one can check if one can write the separate quantization functions in a more efficient way.

Yes, but then it can be closed now? If it should be closed (not merged) either way later?

**Comment by oscargus** [comment]
Yeah, you are right. Also, it now modifies the mantissa and exponent in place.

(#383 made things slower, but #386 implements the same thing as this PR.)

**Pull request closed without merging**
