### PR TITLE
nanobind: port project from pybind11 to nanobind

### PR DESCRIPTION
**Pull request by miklhh**
TODO before merging:

* [X] Make changes listed in [the Nanobind porting guide](https://nanobind.readthedocs.io/en/latest/porting.html)
* [x] Make remaining changes needed to pass unit tests
* [ ] Think of an alternative to pybind11-stubgen
* [x] Valgrind: check for new memory leaks

### CODE REVIEW

**Comment by oscargus** [comment]
>  Think of an alternative to pybind11-stubgen

Manual generation (based on the existing ones)?

**Comment by oscargus** [comment]
Btw, rebase this on main before the next push to see how the benchmarks behave.

**Comment by miklhh** [comment]
> > Think of an alternative to pybind11-stubgen
> 
> Manual generation (based on the existing ones)?

There is the newer stub generator, the [nanobind-stubgen](https://github.com/cansik/nanobind-stubgen) project, which we should probably look into for automatic stub generation. I hope it is mature enough. If not, then it might still be possible to use pybind11-stubgen for stub generation of our nanobind project.

**Comment by miklhh** [comment]
I've made some quick testing of automatic stub generation with the following tools:

* [nanobind-stubgen](https://github.com/cansik/nanobind-stubgen)
* [mypy-stubgen](https://mypy.readthedocs.io/en/stable/stubgen.html)
* [pybind11-stubgen](https://github.com/sizmailov/pybind11-stubgen)

all of which result in pretty major manual modifications required.

**Comment by oscargus** [comment]
Have you rebased this? (The benchmarks are not working then...)

**Comment by oscargus** [comment]
I'd be happy to merge, but would still like to see some preliminary results on the performance and not just trust the statement from nanobind.

**Pull request merged**
